#define EXPOSE_ACTION_INTERNALS
#define EXPOSE_BAP_GLPK_SOLVER_INTERNALS
#define EXPOSE_BAP_GLPK_SOLVER_INTERNALS
#define EXPOSE_BOT_INTERNALS
#define EXPOSE_BUILD_UNITS_INTERNAL
#define EXPOSE_GAME_INTERNALS
#define EXPOSE_GRAPHICS_INTERNALS
#define EXPOSE_GRID_INTERNALS
#define EXPOSE_TURN_INTERNALS
#define EXPOSE_UNITS_INTERNALS

#include "action_test.cpp"
#include "bap_default_solver_test.cpp"
#include "bap_glpk_solver_internal_test.cpp"
#include "bap_glpk_solver_test.cpp"
#include "bap_solver_test.cpp"
#include "bot_test.cpp"
#include "build_units_test.cpp"
#include "game_test.cpp"
#include "graphics_test.cpp"
#include "grid_test.cpp"
#include "list_test.cpp"
#include "turn_test.cpp"
#include "units_test.cpp"